default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: jammer_development
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

test:
  <<: *default
  database: jammer_test
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

production:
  <<: *default
  database: jammer_production
  username: jammer
  password: <%= ENV["JAMMER_DATABASE_PASSWORD"] %>
